name: Deploy To Ec2 

on:
  push:
    branches:
      - main

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Git Hub Repository에 올린 파일들을 불러오기 
              uses: actions/checkout@v4

            - name: JDK 21버전 설치
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: 21

            - name: application.yml 파일 생성
              run : echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./source/back-end/study-buddy/src/main/resources/application.yml

            - name : 테스트 및 빌드하기 
              run : ./gradlew clean build

            - name : 빌드된 파일 이름 변경하기 
              run : mv ./build/libs/*SNAPSHOT.jar ./project.jar

            - name: SCP로 EC2에 빌드된 파일 전송하기 
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                source: project.jar
                target: /home/ubuntu/study-buddy/back-end/tobe

            - name: SSH(원격)로 EC2 접속하기 
              uses : appleboy/ssh-action@master 
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_KEY }}
                script_stop: true
                script: |
                    rm -rf /home/ubuntu/study-buddy/back-end/current
                    mkdir /home/ubuntu/study-buddy/back-end/current
                    mv /home/ubuntu/study-buddy/back-end/tobe/project.jar /home/ubuntu/study-buddy/back-end/current/project.jar
                    cd /home/ubuntu/study-buddy/back-end/current
                    sudo fuser -k -n tcp 8088 || true
                    nohup java -jar project.jar > ./output.log 2>&1 &
                    rm -rf /home/ubuntu/study-buddy/back-end/tobe