name : Github Actions 실행 해보기


on: 
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run : echo "Hello, World!"

      - name: 여러명령어 작성
        run: |
          echo "Hello, World!"
          echo "Hello, World!"

      - name: Github Actions 자체에 저장되어있는 변수 사용해보기 
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID: $GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_REPOSITORY_OWNER_NAME: $GITHUB_REPOSITORY_OWNER_NAME"
          echo "GITHUB_REPOSITORY_OWNER_EMAIL: $GITHUB_REPOSITORY_OWNER_EMAIL"
          echo "GITHUB_REPOSITORY_OWNER_AVATAR_URL: $GITHUB_REPOSITORY_OWNER_AVATAR_URL"  